"""Reusable utilities for applied unsupervised learning workflows."""

from unsup_lab.bayesian import (
    BayesianMixtureResult,
    assignment_uncertainty,
    component_weight_table,
    dirichlet_process_clustering,
    effective_components,
    fit_dirichlet_process_mixture,
)
from unsup_lab.config import RunConfig, dump_config, load_config
from unsup_lab.consensus import (
    ConsensusResult,
    build_coassociation_matrix,
    consensus_clustering,
)
from unsup_lab.data import (
    make_customer_segmentation_data,
    make_document_corpus,
    make_sensor_anomaly_data,
    make_user_item_interactions,
)
from unsup_lab.evaluation import (
    ClusteringMetrics,
    evaluate_clustering,
    evaluate_k_range,
)
from unsup_lab.explain import (
    ClusterSurrogate,
    boundary_cases,
    cluster_exemplars,
    distinctive_features,
    name_clusters,
    persona_cards,
    surrogate_rules,
)
from unsup_lab.graphs import (
    GraphCommunityResult,
    best_partition_by_modularity,
    build_knn_graph,
    detect_communities,
    graph_anomaly_scores,
    make_block_graph,
    modularity,
    node_structural_features,
    spectral_node_embedding,
)
from unsup_lab.nlp import (
    assign_documents,
    clean_text,
    label_topics,
    topic_diversity,
    topic_term_table,
    umass_topic_coherence,
)
from unsup_lab.recommenders import (
    MatrixFactorization,
    build_sparse_interactions,
    discover_item_groups,
    factorize_interactions,
    recommend_for_user,
    similar_items,
)
from unsup_lab.stability import (
    StabilitySummary,
    bootstrap_cluster_stability,
    outlier_sensitivity,
    pairwise_adjusted_mutual_information,
    repeated_run_labels,
    scaling_sensitivity,
    stability_report,
)
from unsup_lab.streaming import (
    detect_drift_points,
    iter_batches,
    monitor_streaming_clusters,
    population_stability_index,
)
from unsup_lab.thresholds import (
    ThresholdChoice,
    compare_thresholds,
    evaluate_threshold,
    knee_threshold,
    mad_threshold,
    otsu_threshold,
    quantile_threshold,
)
from unsup_lab.timeseries import (
    Shapelet,
    cluster_time_series,
    discover_shapelets,
    dtw_distance,
    dtw_distance_matrix,
    matrix_profile,
    shapelet_gap,
    subsequence_distance,
    top_discords,
    top_motifs,
)
from unsup_lab.tracking import RunRecord, best_run, load_runs, log_run

__all__ = [
    "BayesianMixtureResult",
    "ClusterSurrogate",
    "ClusteringMetrics",
    "ConsensusResult",
    "GraphCommunityResult",
    "MatrixFactorization",
    "Shapelet",
    "RunConfig",
    "RunRecord",
    "StabilitySummary",
    "ThresholdChoice",
    "assign_documents",
    "assignment_uncertainty",
    "best_partition_by_modularity",
    "best_run",
    "boundary_cases",
    "bootstrap_cluster_stability",
    "build_coassociation_matrix",
    "build_knn_graph",
    "build_sparse_interactions",
    "clean_text",
    "cluster_time_series",
    "cluster_exemplars",
    "component_weight_table",
    "compare_thresholds",
    "consensus_clustering",
    "detect_communities",
    "detect_drift_points",
    "dirichlet_process_clustering",
    "discover_item_groups",
    "discover_shapelets",
    "distinctive_features",
    "dtw_distance",
    "dtw_distance_matrix",
    "dump_config",
    "effective_components",
    "evaluate_clustering",
    "evaluate_k_range",
    "evaluate_threshold",
    "factorize_interactions",
    "fit_dirichlet_process_mixture",
    "graph_anomaly_scores",
    "iter_batches",
    "label_topics",
    "knee_threshold",
    "load_config",
    "load_runs",
    "log_run",
    "make_block_graph",
    "mad_threshold",
    "make_customer_segmentation_data",
    "make_document_corpus",
    "make_sensor_anomaly_data",
    "make_user_item_interactions",
    "matrix_profile",
    "modularity",
    "name_clusters",
    "monitor_streaming_clusters",
    "node_structural_features",
    "outlier_sensitivity",
    "otsu_threshold",
    "pairwise_adjusted_mutual_information",
    "persona_cards",
    "population_stability_index",
    "recommend_for_user",
    "quantile_threshold",
    "repeated_run_labels",
    "scaling_sensitivity",
    "shapelet_gap",
    "similar_items",
    "spectral_node_embedding",
    "stability_report",
    "subsequence_distance",
    "surrogate_rules",
    "top_discords",
    "top_motifs",
    "topic_diversity",
    "topic_term_table",
    "umass_topic_coherence",
]
